language: node_js
node_js:
  - 13
services:
  - docker
install:
  - echo "Nothing to install"
before_script:
  - echo "No tests"
script:
  - docker --version
  - docker build -t simple-node .
  - docker tag simple-node dragma/simple-node:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dragma/simple-node